export interface Language {
    label: string;
    gemmaCode: string;
    nllbCode: string;
}

export const SUPPORTED_LANGUAGES: Language[] = [
    { label: "English", gemmaCode: "en", nllbCode: "eng_Latn" },
    { label: "Japanese", gemmaCode: "ja", nllbCode: "jpn_Jpan" },
    { label: "French", gemmaCode: "fr", nllbCode: "fra_Latn" },
    { label: "German", gemmaCode: "de", nllbCode: "deu_Latn" },
    { label: "Spanish", gemmaCode: "es", nllbCode: "spa_Latn" },
    { label: "Italian", gemmaCode: "it", nllbCode: "ita_Latn" },
    { label: "Portuguese", gemmaCode: "pt", nllbCode: "por_Latn" },
    { label: "Chinese (Traditional)", gemmaCode: "zh_TW", nllbCode: "zho_Hant" },
    { label: "Korean", gemmaCode: "ko", nllbCode: "kor_Hang" },
    { label: "Russian", gemmaCode: "ru", nllbCode: "rus_Cyrl" },
    { label: "Arabic", gemmaCode: "ar", nllbCode: "ara_Arab" },
    { label: "Hindi", gemmaCode: "hi", nllbCode: "hin_Deva" },
    { label: "Bengali", gemmaCode: "bn", nllbCode: "ben_Beng" },
    { label: "Vietnamese", gemmaCode: "vi", nllbCode: "vie_Latn" },
    { label: "Thai", gemmaCode: "th", nllbCode: "tha_Thai" },
    { label: "Indonesian", gemmaCode: "id", nllbCode: "ind_Latn" },
    { label: "Turkish", gemmaCode: "tr", nllbCode: "tur_Latn" },
    { label: "Dutch", gemmaCode: "nl", nllbCode: "nld_Latn" },
    { label: "Polish", gemmaCode: "pl", nllbCode: "pol_Latn" },
    { label: "Swedish", gemmaCode: "sv", nllbCode: "swe_Latn" },
    { label: "Danish", gemmaCode: "da", nllbCode: "dan_Latn" },
    { label: "Finnish", gemmaCode: "fi", nllbCode: "fin_Latn" },
    { label: "Norwegian", gemmaCode: "no", nllbCode: "nob_Latn" },
    { label: "Czech", gemmaCode: "cs", nllbCode: "ces_Latn" },
    { label: "Greek", gemmaCode: "el", nllbCode: "ell_Latn" },
    { label: "Hungarian", gemmaCode: "hu", nllbCode: "hun_Latn" },
    { label: "Romanian", gemmaCode: "ro", nllbCode: "ron_Latn" },
    { label: "Ukrainian", gemmaCode: "uk", nllbCode: "ukr_Cyrl" },
    { label: "Hebrew", gemmaCode: "he", nllbCode: "heb_Hebr" },
    { label: "Tamil", gemmaCode: "ta", nllbCode: "tam_Taml" },
    { label: "Telugu", gemmaCode: "te", nllbCode: "tel_Telu" },
    { label: "Kannada", gemmaCode: "kn", nllbCode: "kan_Knda" },
    { label: "Malayalam", gemmaCode: "ml", nllbCode: "mal_Mlym" },
    { label: "Marathi", gemmaCode: "mr", nllbCode: "mar_Deva" },
    { label: "Gujarati", gemmaCode: "gu", nllbCode: "guj_Gujr" },
    { label: "Urdu", gemmaCode: "ur", nllbCode: "urd_Arab" },
    { label: "Burmese", gemmaCode: "my", nllbCode: "mya_Mymr" },
    { label: "Nepali", gemmaCode: "ne", nllbCode: "npi_Deva" },
    { label: "Afrikaans", gemmaCode: "af", nllbCode: "afr_Latn" },
    { label: "Swahili", gemmaCode: "sw", nllbCode: "swh_Latn" },
    { label: "Amharic", gemmaCode: "am", nllbCode: "amh_Ethi" },
    { label: "Zulu", gemmaCode: "zu", nllbCode: "zul_Latn" },
    { label: "Bulgarian", gemmaCode: "bg", nllbCode: "bul_Cyrl" },
    { label: "Croatian", gemmaCode: "hr", nllbCode: "hrv_Latn" },
    { label: "Slovak", gemmaCode: "sk", nllbCode: "slk_Latn" },
    { label: "Slovenian", gemmaCode: "sl", nllbCode: "slv_Latn" },
    { label: "Lithuanian", gemmaCode: "lt", nllbCode: "lit_Latn" },
    { label: "Latvian", gemmaCode: "lv", nllbCode: "lav_Latn" },
    { label: "Estonian", gemmaCode: "et", nllbCode: "est_Latn" },
    { label: "Basque", gemmaCode: "eu", nllbCode: "eus_Latn" },
    { label: "Catalan", gemmaCode: "ca", nllbCode: "cat_Latn" },
    { label: "Galician", gemmaCode: "gl", nllbCode: "glg_Latn" },
    { label: "Georgian", gemmaCode: "ka", nllbCode: "kat_Geor" },
    { label: "Azerbaijani", gemmaCode: "az", nllbCode: "azj_Latn" },
    { label: "Persian", gemmaCode: "fa", nllbCode: "fas_Arab" }
];
